# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-01 09:35
from __future__ import unicode_literals

import arca.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('canjeado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Codigo_Descuento_Usuario_Actualizacion', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Codigo_Descuento_Usuario_Cliente', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Codigo_Descuento_Usuario_Creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comercio_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('tiene_descuento_vigencia', models.BooleanField(default=False)),
                ('tiene_descuento_compra_minima', models.BooleanField(default=False)),
                ('tiene_servicio_afiliacion', models.BooleanField(default=False)),
                ('tiene_servicio_crm', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arca.Comercio_Categoria')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.FloatField()),
                ('vigencia', models.IntegerField()),
                ('desc_dia_vigencia', models.IntegerField()),
                ('desc_dia_vigencia_porc_inf', models.FloatField()),
                ('desc_dia_vigencia_porc_sup', models.FloatField()),
                ('desc_compra_minima', models.FloatField()),
                ('desc_compra_minima_porc_inf', models.FloatField()),
                ('desc_compra_minima_porc_sup', models.FloatField()),
                ('tipo_cambio', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Descuento_Usuario_Actualizacion', to=settings.AUTH_USER_MODEL)),
                ('commercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arca.Commercio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Descuento_Usuario_Creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arca.Commercio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.FloatField()),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=arca.models.get_media_url)),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=arca.models.get_media_url)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('baja', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publicidad_Usuario_Actualizacion', to=settings.AUTH_USER_MODEL)),
                ('commercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arca.Commercio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publicidad_Usuario_Creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='codigo_descuento',
            name='descuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arca.Descuento'),
        ),
    ]
