# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='nombre_propietario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
