# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 16:17
from __future__ import unicode_literals

import arca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0002_auto_20170303_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercio',
            name='identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commercio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=arca.models.get_media_url),
        ),
    ]
