# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 15:16
from __future__ import unicode_literals

import arca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0002_comercio_nombre_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to=arca.models.get_media_url),
        ),
    ]
