# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0003_comercio_baner'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='es_gratuito',
            field=models.BooleanField(default=False),
        ),
    ]
