# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0003_auto_20170308_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commercio',
            new_name='Comercio',
        ),
    ]
