# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0005_auto_20170308_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_comercio_categoria', to='arca.Comercio_Categoria'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_comercio_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
