# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0006_auto_20170309_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
