# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0007_descuento_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='commercio',
            new_name='comercio',
        ),
    ]
