# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-18 14:46
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0007_auto_20170508_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio_categoria',
            name='icono',
            field=fontawesome.fields.IconField(blank=True, max_length=60, null=True),
        ),
    ]
