# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0008_auto_20170309_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='desc_compra_minima',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='desc_compra_minima_porc_inf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='desc_compra_minima_porc_sup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='desc_dia_vigencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='desc_dia_vigencia_porc_inf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='desc_dia_vigencia_porc_sup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tipo_cambio',
            field=models.FloatField(default=1),
        ),
    ]
