# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 21:32
from __future__ import unicode_literals

import arca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0011_auto_20170310_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(null=True, upload_to=arca.models.get_media_url)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='codigo_descuento',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='codigo_descuento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='codigo_descuento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='comercio',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
