# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0013_auto_20170312_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo_descuento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Descuento_Empleado_Update', to='arca.Empleado'),
        ),
        migrations.AddField(
            model_name='codigo_descuento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arca.Usuario'),
        ),
        migrations.AddField(
            model_name='codigo_descuento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Descuento_Empleado_Create', to='arca.Empleado'),
        ),
    ]
