# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0015_auto_20170328_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comercio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arca.Comercio')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arca.Codigo_Descuento')),
            ],
        ),
    ]
