# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0016_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='documento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
