# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-22 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('johnmay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='johnmay.Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero', models.CharField(default='', max_length=6)),
                ('tipo_doc', models.CharField(choices=[('101', 'OTRAS ENTRADAS AL INVENTARIO'), ('102', 'OTRAS SALIDAS AL INVENTARIO'), ('201', 'REQUIZA DE ENTRADA'), ('202', 'REQUIZA DE SALIDA')], max_length=3, null=True)),
                ('comentario', models.CharField(max_length=400)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='johnmay.Sucursal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='requiza',
        ),
        migrations.RemoveField(
            model_name='requiza',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='Requiza',
        ),
        migrations.AddField(
            model_name='detalle',
            name='cabecera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='johnmay.Documento'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='johnmay.Producto'),
        ),
    ]
