# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields
import geoposition.fields
import realstate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=realstate.models.get_media_url)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realstate.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(max_length=500)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.FloatField(blank=True, null=True)),
                ('habitaciones', models.IntegerField(blank=True, null=True)),
                ('pisina', models.NullBooleanField()),
                ('cochera', models.IntegerField(blank=True, default=0, null=True)),
                ('banios', models.FloatField(blank=True, default=0, null=True)),
                ('plantas', models.IntegerField(blank=True, default=1, null=True)),
                ('estado_negocio', models.CharField(blank=True, choices=[('PARA RENTA', 'PARA RENTA'), ('PARA VENTA', 'PARA VENTA')], max_length=65, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to=realstate.models.get_media_url)),
                ('descripcion', models.TextField(blank=True, max_length=800, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realstate.Localidad')),
            ],
            options={
                'verbose_name_plural': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='Propiedad_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=300)),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realstate.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('is_corporative', models.BooleanField()),
            ],
            options={
                'verbose_name': 'opcion',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Propietario_Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realstate.Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('icono', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'opcion',
                'verbose_name_plural': 'Tipos de Contacto',
            },
        ),
        migrations.AddField(
            model_name='propietario_contacto',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realstate.Tipo_Contacto'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realstate.Propietario'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realstate.Municipio'),
        ),
        migrations.AddField(
            model_name='foto',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realstate.Propiedad'),
        ),
    ]
