# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=14)),
                ('inss', models.CharField(blank=True, max_length=14, null=True, verbose_name='numero de inss')),
                ('salario', models.FloatField(default=5000.0, verbose_name='salario mensual')),
                ('transporte', models.FloatField(default=1200, verbose_name='viaticos de transporte')),
                ('alimentacion', models.FloatField(default=1200, verbose_name='viaticos de alimentacion')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('cargo', models.CharField(max_length=255)),
                ('cargo_descripcion', models.TextField(max_length=400, verbose_name='breve descripcion del cargo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('contrato', models.FileField(blank=True, null=True, upload_to=b'')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.FloatField(default=0.0)),
                ('inss_patronal', models.FloatField(default=0.0)),
                ('inss_laboral', models.FloatField(default=0.0)),
                ('prestamo', models.FloatField(default=0.0)),
                ('inatec', models.FloatField(default=0.0)),
                ('alimentacion', models.FloatField(default=0.0)),
                ('transporte', models.FloatField(default=0.0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Planilla'),
        ),
    ]
