# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inblensa', '0003_auto_20170704_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='codigo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
