# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-22 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inblensa', '0006_auto_20170904_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='direccion',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='nombre',
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='numero_ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
