# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inblensa', '0008_auto_20170922_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente_codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
