# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('inblensa', 'Can use inblensa'), ('realstate', 'Can use realstate'), ('arca', 'Can use arca')),
            },
        ),
    ]
