# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='media/iconos/'),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='name',
            field=models.CharField(max_length=25, null=True, verbose_name='nombre de la aplicacion'),
        ),
    ]
