# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20170223_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('inblensa', 'Can use inblensa'),),
            },
        ),
        migrations.AlterModelOptions(
            name='aplicacion',
            options={'verbose_name_plural': 'aplicaciones'},
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos'),
        ),
    ]
