# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20170223_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('inblensa', 'Can use inblensa'), ('calculator', 'Can use calculator'))},
        ),
    ]
