# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20170224_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='label',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='etiqueta de la aplicacion'),
        ),
    ]
