# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20170224_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('inblensa', 'Can use inblensa'), ('calculator', 'Can use calculator'))},
        ),
    ]
