# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_opcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
    ]
