# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20170224_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': ()},
        ),
    ]
