# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20170224_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('inblensa', 'Can use inblensa'), ('realstate', 'Can use realstate'), ('arca', 'Can use arca'), ('calculator', 'Can use calculator'))},
        ),
    ]
