# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 19:34
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20170224_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
    ]
