# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-01 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_auto_20170224_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('arca', 'Can use arca'), ('inblensa', 'Can use inblensa'), ('realstate', 'Can use realstate'), ('calculator', 'Can use calculator'))},
        ),
    ]
