# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20170301_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
    ]
