# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20170225_0333'),
        ('control', '0013_auto_20170302_0952'),
    ]

    operations = [
    ]
