# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_merge_20170303_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
    ]
