# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_auto_20170303_2134'),
        ('control', '0015_auto_20170303_1719'),
    ]

    operations = [
    ]
