# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_merge_20170313_1549'),
        ('control', '0016_registro'),
    ]

    operations = [
    ]
